services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mapproxy-server
      - elevation-api 
    networks:
      - swi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"


  # swi-frontend-dev:
  #   image: swi-frontend    
  #   container_name: swi-frontend-dev
  #   environment:
  #     - NUXT_PUBLIC_MAP_DEFAULT_OPACITY=80
  #     - NUXT_PUBLIC_MAP_DEFAULT_LOCATION_X=78.2
  #     - NUXT_PUBLIC_MAP_DEFAULT_LOCATION_Y=15.6
  #     - NUXT_PUBLIC_ENDPOINTS_MAPSERVERS_SEAICE=http://mapserver.localhost/wmts/
  #     - NUXT_PUBLIC_ENDPOINTS_API_ELEVATION=http://api.localhost/oeapi/v1/
  #   restart: unless-stopped
  #   networks:
  #     - swi_network


##### CRON SERVICES #####
# Service to cache the sea ice layer from cryo.met.no for MapProxy. Prod : Cron to be run at 15:05 UTC weekdays
  CRON_seaice_cache_mapproxy:
    image: ghcr.io/unis-svalbard-weather-information/swi-mapcache-seaice:latest
    volumes:
      - ./data/mapproxy/data/latest_seaice:/swi/export
      - ./data/mapproxy/metadata:/swi/metadata
    depends_on:   
      - mapproxy-server
    networks:
      - swi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

# Service to cache the met observations from met.no. Prod: Cron to be run every 10 minutes
  CRON_met_obs_cache:
    image: ghcr.io/unis-svalbard-weather-information/swi-metobs-caching:latest
    volumes:
      - ./data/metobs_cache:/swi/data
    networks:
      - swi_network
    environment:
      - SWI_HOLFUY_API_KEY=$C_MOC_SWI_HOLFUY_API_KEY
      - SWI_FROST_API_KEY=$C_MOC_SWI_FROST_API_KEY
    extra_hosts:
      - "host.docker.internal:host-gateway"

# Service to cache the weather forecast from Arome Arctic (aa). Prod: Cron to be run at 1:30, 7:30, 13:30 and 19:30 UTC
  CRON_aa_for_cache:
    image: ghcr.io/unis-svalbard-weather-information/swi-aromearctic-caching:latest
    volumes:
      - ./data/metobs_cache:/swi/data
    networks:
      - swi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"


##### MAPPROXY SERVICES #####
# Redis service for caching in MapProxy
  redis:
    image: redis:7.4-alpine
    restart: always
    # ports:
      # - "6379:6379"
    command: redis-server --save 20 1 --loglevel verbose --requirepass iamgreatpassword
    networks:
      - swi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

# MapProxy service serving the WMTS service
  mapproxy-server:
    image: ghcr.io/unis-svalbard-weather-information/swi-mapproxy:latest
    # ports:
    #   - "8080:8080"
    volumes:
      - ./data/mapproxy/data/:/mapproxy/data
      - ./data/mapproxy/metadata/:/mapproxy/metadata
      - ./data/mapproxy/cache/:/mapproxy/config/cache_data
    environment:
     - MAPPROXY_REDIS_HOST=redis
     - MAPPROXY_REDIS_PORT=6379
     - MAPPROXY_REDIS_USERNAME=default
     - MAPPROXY_REDIS_PASSWORD=iamgreatpassword
    depends_on:
      - redis
    networks:
      - swi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"



##### BACKEND API SERVICES #####
#Elevation API to get elevation of requested points
  elevation-api:
    image: ghcr.io/unis-svalbard-weather-information/swi-elevationapi:latest
    # ports:
    #   - "8185:8080"
    volumes:
      - ./data/elevation:/code/data
    networks:
      - swi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"


#Meteorological observations and forecast backend API
  metobs-api:
    image: ghcr.io/unis-svalbard-weather-information/swi-metobs-backend:3.0.0-dev05 
    # ports:
    #   - "8185:8080"
    volumes:
      - ./data/metobs_cache:/swi/data
    networks:
      - swi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

#Tilling service for meteorological observations and forecast
  titiller:
    image: ghcr.io/unis-svalbard-weather-information/swi-titiller:latest
    # ports:
    #   - "8185:8080"
    volumes:
      - ./data/metobs_cache/forecast:/swi/data/forecast
    networks:
      - swi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  swi_network:
    driver: bridge